-- Enable RLS
alter table public.videos enable row level security;

-- 1. Comments Table
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  video_id uuid references public.videos(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete set null, -- Null for guest/anonymous if allowed, or strict
  user_name text not null default 'Guest',
  user_avatar text,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Comments
alter table public.comments enable row level security;
create policy "Comments are viewable by everyone" on public.comments for select using (true);
create policy "Users can insert their own comments" on public.comments for insert with check (true); -- Open for now, refine for auth later

-- 2. Likes Table
create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  video_id uuid references public.videos(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  type text check (type in ('like', 'dislike')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(video_id, user_id) -- One like/dislike per video per user
);

-- RLS for Likes
alter table public.likes enable row level security;
create policy "Likes are viewable by everyone" on public.likes for select using (true);
create policy "Users can toggle likes" on public.likes for insert with check (true);
create policy "Users can update likes" on public.likes for update using (true);
create policy "Users can delete likes" on public.likes for delete using (true);

-- 3. Subscriptions (Simple Channel Sub model)
-- Assuming "Channels" are just users or unique strings in this app for now. 
-- Since we don't have a 'channels' table, we'll map subscriber_id (user) to channel_name (string) or channel_user_id.
-- Given current schema uses 'channelName' string in videos, we'll stick to that.
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  subscriber_id uuid references auth.users(id) on delete cascade not null,
  channel_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(subscriber_id, channel_name)
);

-- RLS for Subscriptions
alter table public.subscriptions enable row level security;
create policy "Users view own subs" on public.subscriptions for select using (auth.uid() = subscriber_id);
create policy "Users manage own subs" on public.subscriptions for all using (auth.uid() = subscriber_id);
