-- Create Analytics Events Table for Playback & Upload Telemetry
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null, -- 'playback_start', 'playback_stop', 'buffering_start', 'buffering_end', 'playback_error', 'quality_change', 'abandonment', 'watch_complete', 'upload_start', 'upload_complete', 'upload_error', 'transcode_start', 'transcode_complete', 'thumbnail_gen'
  video_id uuid references public.videos(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  guest_id text,
  details jsonb default '{}'::jsonb not null, -- Stores metadata like buffering duration, selected quality, error details
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS policies for analytics_events
alter table public.analytics_events enable row level security;

create policy "Anyone can insert analytics events" 
on public.analytics_events 
for insert 
with check (true);

create policy "Analytics events readable by admins only" 
on public.analytics_events 
for select 
using (
  auth.role() = 'service_role' or (auth.uid() is not null and exists (
    select 1 from auth.users 
    where id = auth.uid() 
    and (raw_user_meta_data->>'role' = 'admin' or email = 'admin@example.com')
  ))
);

-- Create performance indexes for analytics lookups
create index if not exists idx_analytics_event_type on public.analytics_events(event_type);
create index if not exists idx_analytics_video_id on public.analytics_events(video_id);
create index if not exists idx_analytics_created_at on public.analytics_events(created_at desc);
